<a href="https://colab.research.google.com/github/JoaoVictorDBP/Anime-Recommendation-System/blob/main/AnimeRec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Projeto de Sistema de Recomendação de animes

## API e Requests

In [ ]:
!pip install jikanpy-v4

Collecting jikanpy-v4
  Downloading jikanpy_v4-1.0.2-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from jikanpy-v4) (2.32.4)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from jikanpy-v4) (3.13.0)
Requirement already satisfied: simplejson in /usr/local/lib/python3.12/dist-packages (from jikanpy-v4) (3.20.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->jikanpy-v4) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->jikanpy-v4) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->jikanpy-v4) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->jikanpy-v4) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->jikanpy-v4) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->jikanpy-v4) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->jikanpy-v4) (1.22.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->jikanpy-v4) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->jikanpy-v4) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->jikanpy-v4) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->jikanpy-v4) (2025.10.5)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->jikanpy-v4) (4.15.0)
Downloading jikanpy_v4-1.0.2-py3-none-any.whl (15 kB)
Installing collected packages: jikanpy-v4
Successfully installed jikanpy-v4-1.0.2

In [ ]:
import pandas as pd
import numpy as np
from jikanpy import Jikan
import time

In [ ]:
jikan = Jikan()

In [ ]:
# Get anime details by ID
anime_data = jikan.anime(1) # ID for Cowboy Bebop
print(anime_data['data']['title'])

# Search for anime
search_results = jikan.search('anime', 'Attack on Titan')
print(search_results['data'][0]['title'])

Cowboy Bebop
Shingeki no Kyojin

In [ ]:
# Jojo mangas
best_manga = jikan.search('manga', 'Jojo no Kimyou')
for manga in best_manga['data']:
    print(manga['title'])

JoJo no Kimyou na Bouken Part 3: Stardust Crusaders
Crazy Diamond no Akuryou-teki Shitsuren: JoJo no Kimyou na Bouken yori
JoJo no Kimyou na Bouken Part 6: Stone Ocean
JoJo no Kimyou na Bouken Part 1: Phantom Blood
JoJo no Kimyou na Bouken Part 5: Ougon no Kaze
JoJo no Kimyou na Bouken Part 2: Sentou Chouryuu
JoJo no Kimyou na Bouken Part 4: Diamond wa Kudakenai
JoJo no Kimyou na Bouken Part 9: The JoJoLands
JoJo no Kimyou na Bouken: Crazy Diamond no Akuryou-teki Shitsuren
JoJo no Kimyou na Bouken Part 7: Steel Ball Run
JoJo no Kimyou na Bouken Part 8: JoJolion
Hajishirazu no Purple Haze: JoJo no Kimyou na Bouken yori
JoJo no Kimyou na Bouken
JoJo no Kimyou na Bouken II: Golden Heart/Golden Ring
JoJo no Kimyou na Bouken: Mugen no Ou
Jinsei Jojo na no da
Yarinaoseru Mitai nanode, Kondo koso Akogare no Jijo wo Mezashimasu!
Do Majime Jijo no Konyaku Soudou! Mukuchi na Kishidan Fukudanchou ni Jitsu wa Betabore saretemashita
Koushakuke no Jijo wa Sugata wo Kakusu: Kazoku ni Wasurerareta Moto Reijou wa, Yakushi to Natte Slow Life wo Ouka suru
Charlotte: Toaru Jijo no Shirozukae Monogatari
Meguriyo no Kemono
Kanojo no Jijou
Platinum Seichouki
Chiisai Ko demo Zenbu Hairu Ana
Harukawa-kun to Yuki-sensei no Fudanshi Jijou.

In [ ]:
# Find top 10 mangas right now
top_mangas = jikan.top(type='manga', page=1)
print('Top 10 manga:')
for manga in top_mangas['data'][:10]:
    print(manga['title'])

# Find top 10 animes right now
top_animes = jikan.top(type='anime', page=1)
print('\nTop 10 anime:')
for anime in top_animes['data'][:10]:
    print(anime['title'])

Top 10 manga:
Berserk
JoJo no Kimyou na Bouken Part 7: Steel Ball Run
Vagabond
One Piece
Monster
Guimi Zhi Zhu
Vinland Saga
Slam Dunk
Grand Blue
Fullmetal Alchemist

Top 10 anime:
Sousou no Frieren
Fullmetal Alchemist: Brotherhood
Steins;Gate
Shingeki no Kyojin Season 3 Part 2
Gintama°
Gintama: The Final
One Piece Fan Letter
Chainsaw Man Movie: Reze-hen
Hunter x Hunter (2011)
Gintama'

In [ ]:
# Get general info about a user
def get_user_info(username):
    jikan = Jikan()
    user = jikan.users(username=username, extension='full')
    return user

username = 'JoaoVictorDBP'
user_info1 = get_user_info(username)
print(user_info1)

{'data': {'mal_id': 12934990, 'username': 'JoaoVictorDBP', 'url': 'https://myanimelist.net/profile/JoaoVictorDBP', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/s/common/userimages/23afdf40-8bc7-40fd-9f45-1c022dbb9b1e_225w?s=16be575c86517d74414d2d572bd5595c'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/s/common/userimages/23afdf40-8bc7-40fd-9f45-1c022dbb9b1e_225w?s=16be575c86517d74414d2d572bd5595c'}}, 'last_online': '2025-10-10T10:22:06+00:00', 'gender': 'Male', 'birthday': None, 'location': None, 'joined': '2021-05-27T00:00:00+00:00', 'statistics': {'anime': {'days_watched': 56.2, 'mean_score': 7.81, 'watching': 4, 'completed': 116, 'on_hold': 0, 'dropped': 11, 'plan_to_watch': 11, 'total_entries': 142, 'rewatched': 0, 'episodes_watched': 3342}, 'manga': {'days_read': 11.1, 'mean_score': 8.15, 'reading': 4, 'completed': 17, 'on_hold': 0, 'dropped': 0, 'plan_to_read': 5, 'total_entries': 26, 'reread': 0, 'chapters_read': 1605, 'volumes_read': 190}}, 'favorites': {'anime': [{'mal_id': 50172, 'url': 'https://myanimelist.net/anime/50172/Mob_Psycho_100_III', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1228/125011.jpg?s=5eb894b0f0747b23b6a682eb1db97832', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1228/125011t.jpg?s=5eb894b0f0747b23b6a682eb1db97832', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1228/125011l.jpg?s=5eb894b0f0747b23b6a682eb1db97832'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1228/125011.webp?s=5eb894b0f0747b23b6a682eb1db97832', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1228/125011t.webp?s=5eb894b0f0747b23b6a682eb1db97832', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1228/125011l.webp?s=5eb894b0f0747b23b6a682eb1db97832'}}, 'title': 'Mob Psycho 100 III', 'type': 'TV', 'start_year': 2022}, {'mal_id': 52991, 'url': 'https://myanimelist.net/anime/52991/Sousou_no_Frieren', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg?s=731e5f3f9e6165319ce92176d2b35ee4', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1015/138006t.jpg?s=731e5f3f9e6165319ce92176d2b35ee4', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1015/138006l.jpg?s=731e5f3f9e6165319ce92176d2b35ee4'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1015/138006.webp?s=731e5f3f9e6165319ce92176d2b35ee4', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1015/138006t.webp?s=731e5f3f9e6165319ce92176d2b35ee4', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1015/138006l.webp?s=731e5f3f9e6165319ce92176d2b35ee4'}}, 'title': 'Sousou no Frieren', 'type': 'TV', 'start_year': 2023}, {'mal_id': 55102, 'url': 'https://myanimelist.net/anime/55102/Girls_Band_Cry', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1711/140515.jpg?s=10411b6172ca518df1841e2c0ab502ee', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1711/140515t.jpg?s=10411b6172ca518df1841e2c0ab502ee', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1711/140515l.jpg?s=10411b6172ca518df1841e2c0ab502ee'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1711/140515.webp?s=10411b6172ca518df1841e2c0ab502ee', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1711/140515t.webp?s=10411b6172ca518df1841e2c0ab502ee', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1711/140515l.webp?s=10411b6172ca518df1841e2c0ab502ee'}}, 'title': 'Girls Band Cry', 'type': 'TV', 'start_year': 2024}, {'mal_id': 49387, 'url': 'https://myanimelist.net/anime/49387/Vinland_Saga_Season_2', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1170/124312.jpg?s=84f862c6a9a25247197918d1dc959b40', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1170/124312t.jpg?s=84f862c6a9a25247197918d1dc959b40', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1170/124312l.jpg?s=84f862c6a9a25247197918d1dc959b40'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1170/124312.webp?s=84f862c6a9a25247197918d1dc959b40', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1170/124312t.webp?s=84f862c6a9a25247197918d1dc959b40', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1170/124312l.webp?s=84f862c6a9a25247197918d1dc959b40'}}, 'title': 'Vinland Saga Season 2', 'type': 'TV', 'start_year': 2023}, {'mal_id': 9253, 'url': 'https://myanimelist.net/anime/9253/Steins_Gate', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1935/127974.jpg?s=1da91829b7d0348647278692130c9128', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1935/127974t.jpg?s=1da91829b7d0348647278692130c9128', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1935/127974l.jpg?s=1da91829b7d0348647278692130c9128'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1935/127974.webp?s=1da91829b7d0348647278692130c9128', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1935/127974t.webp?s=1da91829b7d0348647278692130c9128', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1935/127974l.webp?s=1da91829b7d0348647278692130c9128'}}, 'title': 'Steins;Gate', 'type': 'TV', 'start_year': 2011}, {'mal_id': 53393, 'url': 'https://myanimelist.net/anime/53393/Tengoku_Daimakyou', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1121/133132.jpg?s=f812f14c05c234a84e006439d3aca644', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1121/133132t.jpg?s=f812f14c05c234a84e006439d3aca644', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1121/133132l.jpg?s=f812f14c05c234a84e006439d3aca644'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1121/133132.webp?s=f812f14c05c234a84e006439d3aca644', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1121/133132t.webp?s=f812f14c05c234a84e006439d3aca644', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1121/133132l.webp?s=f812f14c05c234a84e006439d3aca644'}}, 'title': 'Tengoku Daimakyou', 'type': 'TV', 'start_year': 2023}, {'mal_id': 60489, 'url': 'https://myanimelist.net/anime/60489/Takopii_no_Genzai', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1182/149879.jpg?s=8b35e3a7c1fb6524b22fd706d99ed511', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1182/149879t.jpg?s=8b35e3a7c1fb6524b22fd706d99ed511', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1182/149879l.jpg?s=8b35e3a7c1fb6524b22fd706d99ed511'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1182/149879.webp?s=8b35e3a7c1fb6524b22fd706d99ed511', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1182/149879t.webp?s=8b35e3a7c1fb6524b22fd706d99ed511', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1182/149879l.webp?s=8b35e3a7c1fb6524b22fd706d99ed511'}}, 'title': 'Takopii no Genzai', 'type': 'ONA', 'start_year': 2025}, {'mal_id': 1535, 'url': 'https://myanimelist.net/anime/1535/Death_Note', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1079/138100.jpg?s=a6cff3053b39332406b7a838bf10b5b2', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1079/138100t.jpg?s=a6cff3053b39332406b7a838bf10b5b2', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1079/138100l.jpg?s=a6cff3053b39332406b7a838bf10b5b2'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1079/138100.webp?s=a6cff3053b39332406b7a838bf10b5b2', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1079/138100t.webp?s=a6cff3053b39332406b7a838bf10b5b2', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1079/138100l.webp?s=a6cff3053b39332406b7a838bf10b5b2'}}, 'title': 'Death Note', 'type': 'TV', 'start_year': 2006}, {'mal_id': 28851, 'url': 'https://myanimelist.net/anime/28851/Koe_no_Katachi', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1122/96435.jpg?s=ab8cd56e0b6c42df1b7cbf7147f38faf', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1122/96435t.jpg?s=ab8cd56e0b6c42df1b7cbf7147f38faf', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1122/96435l.jpg?s=ab8cd56e0b6c42df1b7cbf7147f38faf'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1122/96435.webp?s=ab8cd56e0b6c42df1b7cbf7147f38faf', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1122/96435t.webp?s=ab8cd56e0b6c42df1b7cbf7147f38faf', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1122/96435l.webp?s=ab8cd56e0b6c42df1b7cbf7147f38faf'}}, 'title': 'Koe no Katachi', 'type': 'Movie', 'start_year': 2016}, {'mal_id': 11061, 'url': 'https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg?s=504a4913520f83c69ba65d7dcc5b70bb', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1337/99013t.jpg?s=504a4913520f83c69ba65d7dcc5b70bb', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1337/99013l.jpg?s=504a4913520f83c69ba65d7dcc5b70bb'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1337/99013.webp?s=504a4913520f83c69ba65d7dcc5b70bb', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1337/99013t.webp?s=504a4913520f83c69ba65d7dcc5b70bb', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1337/99013l.webp?s=504a4913520f83c69ba65d7dcc5b70bb'}}, 'title': 'Hunter x Hunter (2011)', 'type': 'TV', 'start_year': 2011}], 'manga': [{'mal_id': 2, 'url': 'https://myanimelist.net/manga/2/Berserk', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/1/157897.jpg?s=9dadda757ebc02c67b4dbdb873e0fd5f', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/1/157897t.jpg?s=9dadda757ebc02c67b4dbdb873e0fd5f', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/1/157897l.jpg?s=9dadda757ebc02c67b4dbdb873e0fd5f'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/1/157897.webp?s=9dadda757ebc02c67b4dbdb873e0fd5f', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/1/157897t.webp?s=9dadda757ebc02c67b4dbdb873e0fd5f', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/1/157897l.webp?s=9dadda757ebc02c67b4dbdb873e0fd5f'}}, 'title': 'Berserk', 'type': 'Manga', 'start_year': 1989}, {'mal_id': 642, 'url': 'https://myanimelist.net/manga/642/Vinland_Saga', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/2/188925.jpg?s=967b5e2908beae63c5c22e61176ef728', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/2/188925t.jpg?s=967b5e2908beae63c5c22e61176ef728', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/2/188925l.jpg?s=967b5e2908beae63c5c22e61176ef728'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/2/188925.webp?s=967b5e2908beae63c5c22e61176ef728', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/2/188925t.webp?s=967b5e2908beae63c5c22e61176ef728', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/2/188925l.webp?s=967b5e2908beae63c5c22e61176ef728'}}, 'title': 'Vinland Saga', 'type': 'Manga', 'start_year': 2005}, {'mal_id': 144267, 'url': 'https://myanimelist.net/manga/144267/Kaoru_Hana_wa_Rin_to_Saku', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/5/256607.jpg?s=a427142a00fec1d6a61f417395be8827', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/5/256607t.jpg?s=a427142a00fec1d6a61f417395be8827', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/5/256607l.jpg?s=a427142a00fec1d6a61f417395be8827'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/5/256607.webp?s=a427142a00fec1d6a61f417395be8827', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/5/256607t.webp?s=a427142a00fec1d6a61f417395be8827', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/5/256607l.webp?s=a427142a00fec1d6a61f417395be8827'}}, 'title': 'Kaoru Hana wa Rin to Saku', 'type': 'Manga', 'start_year': 2021}, {'mal_id': 35243, 'url': 'https://myanimelist.net/manga/35243/Haikyuu', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/2/258225.jpg?s=9e3907dee498487d81034e089cadb45e', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/2/258225t.jpg?s=9e3907dee498487d81034e089cadb45e', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/2/258225l.jpg?s=9e3907dee498487d81034e089cadb45e'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/2/258225.webp?s=9e3907dee498487d81034e089cadb45e', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/2/258225t.webp?s=9e3907dee498487d81034e089cadb45e', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/2/258225l.webp?s=9e3907dee498487d81034e089cadb45e'}}, 'title': 'Haikyuu!!', 'type': 'Manga', 'start_year': 2012}, {'mal_id': 111745, 'url': 'https://myanimelist.net/manga/111745/Tengoku_Daimakyou', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/2/210308.jpg?s=2756c141de3230c2dca98089c9c6dfcc', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/2/210308t.jpg?s=2756c141de3230c2dca98089c9c6dfcc', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/2/210308l.jpg?s=2756c141de3230c2dca98089c9c6dfcc'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/2/210308.webp?s=2756c141de3230c2dca98089c9c6dfcc', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/2/210308t.webp?s=2756c141de3230c2dca98089c9c6dfcc', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/2/210308l.webp?s=2756c141de3230c2dca98089c9c6dfcc'}}, 'title': 'Tengoku Daimakyou', 'type': 'Manga', 'start_year': 2018}, {'mal_id': 138673, 'url': 'https://myanimelist.net/manga/138673/Look_Back', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/3/249833.jpg?s=8ad2ea190446fe25e08acdb1f8db0ad6', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/3/249833t.jpg?s=8ad2ea190446fe25e08acdb1f8db0ad6', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/3/249833l.jpg?s=8ad2ea190446fe25e08acdb1f8db0ad6'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/3/249833.webp?s=8ad2ea190446fe25e08acdb1f8db0ad6', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/3/249833t.webp?s=8ad2ea190446fe25e08acdb1f8db0ad6', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/3/249833l.webp?s=8ad2ea190446fe25e08acdb1f8db0ad6'}}, 'title': 'Look Back', 'type': 'Manga', 'start_year': 2021}, {'mal_id': 88660, 'url': 'https://myanimelist.net/manga/88660/Yagate_Kimi_ni_Naru', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/1/232311.jpg?s=1de15ab027004d9ce38b2a389bf17146', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/1/232311t.jpg?s=1de15ab027004d9ce38b2a389bf17146', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/1/232311l.jpg?s=1de15ab027004d9ce38b2a389bf17146'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/1/232311.webp?s=1de15ab027004d9ce38b2a389bf17146', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/1/232311t.webp?s=1de15ab027004d9ce38b2a389bf17146', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/1/232311l.webp?s=1de15ab027004d9ce38b2a389bf17146'}}, 'title': 'Yagate Kimi ni Naru', 'type': 'Manga', 'start_year': 2015}], 'characters': [{'mal_id': 109929, 'url': 'https://myanimelist.net/character/109929/Shigeo_Kageyama', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/6/343344.jpg?s=d8bbc2918eb10ea1e1dad7d9b1aed0ce'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/6/343344.webp?s=d8bbc2918eb10ea1e1dad7d9b1aed0ce', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/6/343344t.webp?s=d8bbc2918eb10ea1e1dad7d9b1aed0ce'}}, 'name': 'Kageyama, Shigeo'}, {'mal_id': 10138, 'url': 'https://myanimelist.net/character/10138/Thorfinn', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/9/309871.jpg?s=0aaed2145f446dae41038a8cdbdb83fe'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/9/309871.webp?s=0aaed2145f446dae41038a8cdbdb83fe', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/9/309871t.webp?s=0aaed2145f446dae41038a8cdbdb83fe'}}, 'name': 'Thorfinn'}, {'mal_id': 64769, 'url': 'https://myanimelist.net/character/64769/Shouyou_Hinata', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/11/243919.jpg?s=1c767fb4331aa08ab5c1932ca027a9f1'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/11/243919.webp?s=1c767fb4331aa08ab5c1932ca027a9f1', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/11/243919t.webp?s=1c767fb4331aa08ab5c1932ca027a9f1'}}, 'name': 'Hinata, Shouyou'}, {'mal_id': 35252, 'url': 'https://myanimelist.net/character/35252/Rintarou_Okabe', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/6/122643.jpg?s=95760ef16d9a25f661d77ebb4a29a4d2'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/6/122643.webp?s=95760ef16d9a25f661d77ebb4a29a4d2', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/6/122643t.webp?s=95760ef16d9a25f661d77ebb4a29a4d2'}}, 'name': 'Okabe, Rintarou'}, {'mal_id': 422, 'url': 'https://myanimelist.net/character/422/Guts', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/13/284125.jpg?s=40fb578cc3f887db6d64a3ab40112d53'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/13/284125.webp?s=40fb578cc3f887db6d64a3ab40112d53', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/13/284125t.webp?s=40fb578cc3f887db6d64a3ab40112d53'}}, 'name': 'Guts'}, {'mal_id': 210349, 'url': 'https://myanimelist.net/character/210349/Subaru_Hoshina', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/10/586474.jpg?s=2cd420b2d22db5614a421a5afc606ff0'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/10/586474.webp?s=2cd420b2d22db5614a421a5afc606ff0', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/10/586474t.webp?s=2cd420b2d22db5614a421a5afc606ff0'}}, 'name': 'Hoshina, Subaru'}, {'mal_id': 211617, 'url': 'https://myanimelist.net/character/211617/Rintarou_Tsumugi', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/15/586473.jpg?s=463140b7c3340e4140329052eebdd526'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/15/586473.webp?s=463140b7c3340e4140329052eebdd526', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/15/586473t.webp?s=463140b7c3340e4140329052eebdd526'}}, 'name': 'Tsumugi, Rintarou'}, {'mal_id': 230308, 'url': 'https://myanimelist.net/character/230308/Subaru_Awa', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/16/512878.jpg?s=6c006510940e134e3bfda4279f86de0d'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/16/512878.webp?s=6c006510940e134e3bfda4279f86de0d', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/16/512878t.webp?s=6c006510940e134e3bfda4279f86de0d'}}, 'name': 'Awa, Subaru'}, {'mal_id': 131589, 'url': 'https://myanimelist.net/character/131589/Hild', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/3/483045.jpg?s=d526bbeb66fc8576d2b6fce340999b65'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/3/483045.webp?s=d526bbeb66fc8576d2b6fce340999b65', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/3/483045t.webp?s=d526bbeb66fc8576d2b6fce340999b65'}}, 'name': 'Hild'}, {'mal_id': 184947, 'url': 'https://myanimelist.net/character/184947/Frieren', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/7/525105.jpg?s=667cf468daf3f6f6ff9556ffe5b58836'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/7/525105.w

In [ ]:
# Get user favorite animes
def get_user_anime_ratings(username):
    jikan = Jikan()
    user = jikan.users(username=username, extension='favorites')
    return user

username = 'JoaoVictorDBP'
user_anime_ratings = get_user_anime_ratings(username)
print(user_anime_ratings)

{'data': {'anime': [{'mal_id': 50172, 'url': 'https://myanimelist.net/anime/50172/Mob_Psycho_100_III', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1228/125011.jpg?s=5eb894b0f0747b23b6a682eb1db97832', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1228/125011t.jpg?s=5eb894b0f0747b23b6a682eb1db97832', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1228/125011l.jpg?s=5eb894b0f0747b23b6a682eb1db97832'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1228/125011.webp?s=5eb894b0f0747b23b6a682eb1db97832', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1228/125011t.webp?s=5eb894b0f0747b23b6a682eb1db97832', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1228/125011l.webp?s=5eb894b0f0747b23b6a682eb1db97832'}}, 'title': 'Mob Psycho 100 III', 'type': 'TV', 'start_year': 2022}, {'mal_id': 52991, 'url': 'https://myanimelist.net/anime/52991/Sousou_no_Frieren', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg?s=731e5f3f9e6165319ce92176d2b35ee4', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1015/138006t.jpg?s=731e5f3f9e6165319ce92176d2b35ee4', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1015/138006l.jpg?s=731e5f3f9e6165319ce92176d2b35ee4'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1015/138006.webp?s=731e5f3f9e6165319ce92176d2b35ee4', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1015/138006t.webp?s=731e5f3f9e6165319ce92176d2b35ee4', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1015/138006l.webp?s=731e5f3f9e6165319ce92176d2b35ee4'}}, 'title': 'Sousou no Frieren', 'type': 'TV', 'start_year': 2023}, {'mal_id': 55102, 'url': 'https://myanimelist.net/anime/55102/Girls_Band_Cry', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1711/140515.jpg?s=10411b6172ca518df1841e2c0ab502ee', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1711/140515t.jpg?s=10411b6172ca518df1841e2c0ab502ee', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1711/140515l.jpg?s=10411b6172ca518df1841e2c0ab502ee'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1711/140515.webp?s=10411b6172ca518df1841e2c0ab502ee', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1711/140515t.webp?s=10411b6172ca518df1841e2c0ab502ee', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1711/140515l.webp?s=10411b6172ca518df1841e2c0ab502ee'}}, 'title': 'Girls Band Cry', 'type': 'TV', 'start_year': 2024}, {'mal_id': 49387, 'url': 'https://myanimelist.net/anime/49387/Vinland_Saga_Season_2', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1170/124312.jpg?s=84f862c6a9a25247197918d1dc959b40', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1170/124312t.jpg?s=84f862c6a9a25247197918d1dc959b40', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1170/124312l.jpg?s=84f862c6a9a25247197918d1dc959b40'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1170/124312.webp?s=84f862c6a9a25247197918d1dc959b40', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1170/124312t.webp?s=84f862c6a9a25247197918d1dc959b40', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1170/124312l.webp?s=84f862c6a9a25247197918d1dc959b40'}}, 'title': 'Vinland Saga Season 2', 'type': 'TV', 'start_year': 2023}, {'mal_id': 9253, 'url': 'https://myanimelist.net/anime/9253/Steins_Gate', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1935/127974.jpg?s=1da91829b7d0348647278692130c9128', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1935/127974t.jpg?s=1da91829b7d0348647278692130c9128', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1935/127974l.jpg?s=1da91829b7d0348647278692130c9128'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1935/127974.webp?s=1da91829b7d0348647278692130c9128', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1935/127974t.webp?s=1da91829b7d0348647278692130c9128', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1935/127974l.webp?s=1da91829b7d0348647278692130c9128'}}, 'title': 'Steins;Gate', 'type': 'TV', 'start_year': 2011}, {'mal_id': 53393, 'url': 'https://myanimelist.net/anime/53393/Tengoku_Daimakyou', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1121/133132.jpg?s=f812f14c05c234a84e006439d3aca644', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1121/133132t.jpg?s=f812f14c05c234a84e006439d3aca644', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1121/133132l.jpg?s=f812f14c05c234a84e006439d3aca644'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1121/133132.webp?s=f812f14c05c234a84e006439d3aca644', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1121/133132t.webp?s=f812f14c05c234a84e006439d3aca644', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1121/133132l.webp?s=f812f14c05c234a84e006439d3aca644'}}, 'title': 'Tengoku Daimakyou', 'type': 'TV', 'start_year': 2023}, {'mal_id': 60489, 'url': 'https://myanimelist.net/anime/60489/Takopii_no_Genzai', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1182/149879.jpg?s=8b35e3a7c1fb6524b22fd706d99ed511', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1182/149879t.jpg?s=8b35e3a7c1fb6524b22fd706d99ed511', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1182/149879l.jpg?s=8b35e3a7c1fb6524b22fd706d99ed511'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1182/149879.webp?s=8b35e3a7c1fb6524b22fd706d99ed511', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1182/149879t.webp?s=8b35e3a7c1fb6524b22fd706d99ed511', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1182/149879l.webp?s=8b35e3a7c1fb6524b22fd706d99ed511'}}, 'title': 'Takopii no Genzai', 'type': 'ONA', 'start_year': 2025}, {'mal_id': 1535, 'url': 'https://myanimelist.net/anime/1535/Death_Note', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1079/138100.jpg?s=a6cff3053b39332406b7a838bf10b5b2', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1079/138100t.jpg?s=a6cff3053b39332406b7a838bf10b5b2', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1079/138100l.jpg?s=a6cff3053b39332406b7a838bf10b5b2'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1079/138100.webp?s=a6cff3053b39332406b7a838bf10b5b2', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1079/138100t.webp?s=a6cff3053b39332406b7a838bf10b5b2', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1079/138100l.webp?s=a6cff3053b39332406b7a838bf10b5b2'}}, 'title': 'Death Note', 'type': 'TV', 'start_year': 2006}, {'mal_id': 28851, 'url': 'https://myanimelist.net/anime/28851/Koe_no_Katachi', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1122/96435.jpg?s=ab8cd56e0b6c42df1b7cbf7147f38faf', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1122/96435t.jpg?s=ab8cd56e0b6c42df1b7cbf7147f38faf', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1122/96435l.jpg?s=ab8cd56e0b6c42df1b7cbf7147f38faf'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1122/96435.webp?s=ab8cd56e0b6c42df1b7cbf7147f38faf', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1122/96435t.webp?s=ab8cd56e0b6c42df1b7cbf7147f38faf', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1122/96435l.webp?s=ab8cd56e0b6c42df1b7cbf7147f38faf'}}, 'title': 'Koe no Katachi', 'type': 'Movie', 'start_year': 2016}, {'mal_id': 11061, 'url': 'https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg?s=504a4913520f83c69ba65d7dcc5b70bb', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1337/99013t.jpg?s=504a4913520f83c69ba65d7dcc5b70bb', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1337/99013l.jpg?s=504a4913520f83c69ba65d7dcc5b70bb'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/anime/1337/99013.webp?s=504a4913520f83c69ba65d7dcc5b70bb', 'small_image_url': 'https://cdn.myanimelist.net/images/anime/1337/99013t.webp?s=504a4913520f83c69ba65d7dcc5b70bb', 'large_image_url': 'https://cdn.myanimelist.net/images/anime/1337/99013l.webp?s=504a4913520f83c69ba65d7dcc5b70bb'}}, 'title': 'Hunter x Hunter (2011)', 'type': 'TV', 'start_year': 2011}], 'manga': [{'mal_id': 2, 'url': 'https://myanimelist.net/manga/2/Berserk', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/1/157897.jpg?s=9dadda757ebc02c67b4dbdb873e0fd5f', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/1/157897t.jpg?s=9dadda757ebc02c67b4dbdb873e0fd5f', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/1/157897l.jpg?s=9dadda757ebc02c67b4dbdb873e0fd5f'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/1/157897.webp?s=9dadda757ebc02c67b4dbdb873e0fd5f', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/1/157897t.webp?s=9dadda757ebc02c67b4dbdb873e0fd5f', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/1/157897l.webp?s=9dadda757ebc02c67b4dbdb873e0fd5f'}}, 'title': 'Berserk', 'type': 'Manga', 'start_year': 1989}, {'mal_id': 642, 'url': 'https://myanimelist.net/manga/642/Vinland_Saga', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/2/188925.jpg?s=967b5e2908beae63c5c22e61176ef728', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/2/188925t.jpg?s=967b5e2908beae63c5c22e61176ef728', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/2/188925l.jpg?s=967b5e2908beae63c5c22e61176ef728'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/2/188925.webp?s=967b5e2908beae63c5c22e61176ef728', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/2/188925t.webp?s=967b5e2908beae63c5c22e61176ef728', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/2/188925l.webp?s=967b5e2908beae63c5c22e61176ef728'}}, 'title': 'Vinland Saga', 'type': 'Manga', 'start_year': 2005}, {'mal_id': 144267, 'url': 'https://myanimelist.net/manga/144267/Kaoru_Hana_wa_Rin_to_Saku', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/5/256607.jpg?s=a427142a00fec1d6a61f417395be8827', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/5/256607t.jpg?s=a427142a00fec1d6a61f417395be8827', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/5/256607l.jpg?s=a427142a00fec1d6a61f417395be8827'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/5/256607.webp?s=a427142a00fec1d6a61f417395be8827', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/5/256607t.webp?s=a427142a00fec1d6a61f417395be8827', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/5/256607l.webp?s=a427142a00fec1d6a61f417395be8827'}}, 'title': 'Kaoru Hana wa Rin to Saku', 'type': 'Manga', 'start_year': 2021}, {'mal_id': 35243, 'url': 'https://myanimelist.net/manga/35243/Haikyuu', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/2/258225.jpg?s=9e3907dee498487d81034e089cadb45e', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/2/258225t.jpg?s=9e3907dee498487d81034e089cadb45e', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/2/258225l.jpg?s=9e3907dee498487d81034e089cadb45e'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/2/258225.webp?s=9e3907dee498487d81034e089cadb45e', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/2/258225t.webp?s=9e3907dee498487d81034e089cadb45e', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/2/258225l.webp?s=9e3907dee498487d81034e089cadb45e'}}, 'title': 'Haikyuu!!', 'type': 'Manga', 'start_year': 2012}, {'mal_id': 111745, 'url': 'https://myanimelist.net/manga/111745/Tengoku_Daimakyou', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/2/210308.jpg?s=2756c141de3230c2dca98089c9c6dfcc', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/2/210308t.jpg?s=2756c141de3230c2dca98089c9c6dfcc', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/2/210308l.jpg?s=2756c141de3230c2dca98089c9c6dfcc'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/2/210308.webp?s=2756c141de3230c2dca98089c9c6dfcc', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/2/210308t.webp?s=2756c141de3230c2dca98089c9c6dfcc', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/2/210308l.webp?s=2756c141de3230c2dca98089c9c6dfcc'}}, 'title': 'Tengoku Daimakyou', 'type': 'Manga', 'start_year': 2018}, {'mal_id': 138673, 'url': 'https://myanimelist.net/manga/138673/Look_Back', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/3/249833.jpg?s=8ad2ea190446fe25e08acdb1f8db0ad6', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/3/249833t.jpg?s=8ad2ea190446fe25e08acdb1f8db0ad6', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/3/249833l.jpg?s=8ad2ea190446fe25e08acdb1f8db0ad6'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/3/249833.webp?s=8ad2ea190446fe25e08acdb1f8db0ad6', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/3/249833t.webp?s=8ad2ea190446fe25e08acdb1f8db0ad6', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/3/249833l.webp?s=8ad2ea190446fe25e08acdb1f8db0ad6'}}, 'title': 'Look Back', 'type': 'Manga', 'start_year': 2021}, {'mal_id': 88660, 'url': 'https://myanimelist.net/manga/88660/Yagate_Kimi_ni_Naru', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/1/232311.jpg?s=1de15ab027004d9ce38b2a389bf17146', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/1/232311t.jpg?s=1de15ab027004d9ce38b2a389bf17146', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/1/232311l.jpg?s=1de15ab027004d9ce38b2a389bf17146'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/1/232311.webp?s=1de15ab027004d9ce38b2a389bf17146', 'small_image_url': 'https://cdn.myanimelist.net/images/manga/1/232311t.webp?s=1de15ab027004d9ce38b2a389bf17146', 'large_image_url': 'https://cdn.myanimelist.net/images/manga/1/232311l.webp?s=1de15ab027004d9ce38b2a389bf17146'}}, 'title': 'Yagate Kimi ni Naru', 'type': 'Manga', 'start_year': 2015}], 'characters': [{'mal_id': 109929, 'url': 'https://myanimelist.net/character/109929/Shigeo_Kageyama', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/6/343344.jpg?s=d8bbc2918eb10ea1e1dad7d9b1aed0ce'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/6/343344.webp?s=d8bbc2918eb10ea1e1dad7d9b1aed0ce', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/6/343344t.webp?s=d8bbc2918eb10ea1e1dad7d9b1aed0ce'}}, 'name': 'Kageyama, Shigeo'}, {'mal_id': 10138, 'url': 'https://myanimelist.net/character/10138/Thorfinn', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/9/309871.jpg?s=0aaed2145f446dae41038a8cdbdb83fe'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/9/309871.webp?s=0aaed2145f446dae41038a8cdbdb83fe', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/9/309871t.webp?s=0aaed2145f446dae41038a8cdbdb83fe'}}, 'name': 'Thorfinn'}, {'mal_id': 64769, 'url': 'https://myanimelist.net/character/64769/Shouyou_Hinata', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/11/243919.jpg?s=1c767fb4331aa08ab5c1932ca027a9f1'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/11/243919.webp?s=1c767fb4331aa08ab5c1932ca027a9f1', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/11/243919t.webp?s=1c767fb4331aa08ab5c1932ca027a9f1'}}, 'name': 'Hinata, Shouyou'}, {'mal_id': 35252, 'url': 'https://myanimelist.net/character/35252/Rintarou_Okabe', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/6/122643.jpg?s=95760ef16d9a25f661d77ebb4a29a4d2'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/6/122643.webp?s=95760ef16d9a25f661d77ebb4a29a4d2', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/6/122643t.webp?s=95760ef16d9a25f661d77ebb4a29a4d2'}}, 'name': 'Okabe, Rintarou'}, {'mal_id': 422, 'url': 'https://myanimelist.net/character/422/Guts', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/13/284125.jpg?s=40fb578cc3f887db6d64a3ab40112d53'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/13/284125.webp?s=40fb578cc3f887db6d64a3ab40112d53', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/13/284125t.webp?s=40fb578cc3f887db6d64a3ab40112d53'}}, 'name': 'Guts'}, {'mal_id': 210349, 'url': 'https://myanimelist.net/character/210349/Subaru_Hoshina', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/10/586474.jpg?s=2cd420b2d22db5614a421a5afc606ff0'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/10/586474.webp?s=2cd420b2d22db5614a421a5afc606ff0', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/10/586474t.webp?s=2cd420b2d22db5614a421a5afc606ff0'}}, 'name': 'Hoshina, Subaru'}, {'mal_id': 211617, 'url': 'https://myanimelist.net/character/211617/Rintarou_Tsumugi', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/15/586473.jpg?s=463140b7c3340e4140329052eebdd526'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/15/586473.webp?s=463140b7c3340e4140329052eebdd526', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/15/586473t.webp?s=463140b7c3340e4140329052eebdd526'}}, 'name': 'Tsumugi, Rintarou'}, {'mal_id': 230308, 'url': 'https://myanimelist.net/character/230308/Subaru_Awa', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/16/512878.jpg?s=6c006510940e134e3bfda4279f86de0d'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/16/512878.webp?s=6c006510940e134e3bfda4279f86de0d', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/16/512878t.webp?s=6c006510940e134e3bfda4279f86de0d'}}, 'name': 'Awa, Subaru'}, {'mal_id': 131589, 'url': 'https://myanimelist.net/character/131589/Hild', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/3/483045.jpg?s=d526bbeb66fc8576d2b6fce340999b65'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/3/483045.webp?s=d526bbeb66fc8576d2b6fce340999b65', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/3/483045t.webp?s=d526bbeb66fc8576d2b6fce340999b65'}}, 'name': 'Hild'}, {'mal_id': 184947, 'url': 'https://myanimelist.net/character/184947/Frieren', 'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/characters/7/525105.jpg?s=667cf468daf3f6f6ff9556ffe5b58836'}, 'webp': {'image_url': 'https://cdn.myanimelist.net/images/characters/7/525105.webp?s=667cf468daf3f6f6ff9556ffe5b58836', 'small_image_url': 'https://cdn.myanimelist.net/images/characters/7/525105t.webp?s=667cf468daf3f6f6ff9556ffe5b58836'}}, 'name': 'Frieren'}], 'people': []}, 'jikan_url': 'https://api.jikan.moe/v4/users/joaovictordbp/favorites', 'headers': {'Server': 'nginx/1.24.0', 'Date': 'Fri, 10 Oct 2025 21:22:07 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Cache-Control': 'public, s-maxage=300', 'x-request-fingerprint': 'request:users:bdaee2e6f4039d1224f31b6493ce65493c310bca', 'expires': 'Fri, 10 Oct 2025 21:27:06 GMT', 'last-modified': 'Fri, 10 Oct 2025 21:22:06 GMT', 'access-control-allow-origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'X-Cache-Status': 'MISS', 'X-Powered-By': 'the-power-of-friendship'}}

# Objetivos a seguir

1. Coletar Top 1000 Animes
2. Extrair atributos e salvar em DataFrame
3. Fazer pré-processamento (One-Hot + TF-IDF)
4. Calcular matriz de similaridade
5. Receber lista de animes favoritos do usuário e recomendar

In [ ]:
# Analisando as caracteristicas disponíveis de cada anime

anime_details = jikan.anime(1)
print(anime_details['data'].keys())

dict_keys(['mal_id', 'url', 'images', 'trailer', 'approved', 'titles', 'title', 'title_english', 'title_japanese', 'title_synonyms', 'type', 'source', 'episodes', 'status', 'airing', 'aired', 'duration', 'rating', 'score', 'scored_by', 'rank', 'popularity', 'members', 'favorites', 'synopsis', 'background', 'season', 'year', 'broadcast', 'producers', 'licensors', 'studios', 'genres', 'explicit_genres', 'themes', 'demographics'])

In [ ]:
# Pega informações dos TOP 1000 animes

anime_list = []

def top_1000():
  for i in range(1, 41):
    print(f"Coletando página {i}...")

    try:
      all_anime = jikan.top('anime', page=i)

      for anime in all_anime['data']:
        anime_info = {
                'mal_id': anime.get('mal_id'),
                'title': anime.get('title'),
                'type': anime.get('type'),
                'score': anime.get('score'),
                'episodes': anime.get('episodes'),
                'rank': anime.get('rank'),
                'popularity': anime.get('popularity'),
                'genres': ', '.join([g['name'] for g in anime.get('genres', [])]),
                'synopsis': anime.get('synopsis'),
                'background': anime.get('background'),
                'themes': ', '.join([t['name'] for t in anime.get('themes', [])]),
                'demographics': ', '.join([d['name'] for d in anime.get('demographics', [])])
        }
        anime_list.append(anime_info)

    except Exception as e:
          print(f"Erro na página {i}: {e}")
          print("Aguardando 10 segundos e tentando novamente...")
          time.sleep(10)
          continue

    time.sleep(1)  # 1 segundo entre requisições

# Executa a função

top_1000()

Coletando página 1...
Coletando página 2...
Coletando página 3...
Coletando página 4...
Coletando página 5...
Coletando página 6...
Coletando página 7...
Coletando página 8...
Coletando página 9...
Coletando página 10...
Coletando página 11...
Coletando página 12...
Coletando página 13...
Coletando página 14...
Coletando página 15...
Coletando página 16...
Coletando página 17...
Coletando página 18...
Coletando página 19...
Coletando página 20...
Coletando página 21...
Coletando página 22...
Coletando página 23...
Coletando página 24...
Coletando página 25...
Coletando página 26...
Coletando página 27...
Coletando página 28...
Coletando página 29...
Coletando página 30...
Coletando página 31...
Coletando página 32...
Coletando página 33...
Coletando página 34...
Coletando página 35...
Coletando página 36...
Coletando página 37...
Coletando página 38...
Coletando página 39...
Coletando página 40...

In [ ]:
# Cria DataFrame com os dados obtidos

df_anime = pd.DataFrame(anime_list)
df_anime

,mal_id,title,type,score,episodes,rank,popularity,genres,synopsis,background,themes,demographics
0,52991,Sousou no Frieren,TV,9.29,28.0,1.0,128,"Adventure, Drama, Fantasy",During their decade-long quest to defeat the D...,Sousou no Frieren was released on Blu-ray and ...,,Shounen
1,5114,Fullmetal Alchemist: Brotherhood,TV,9.10,64.0,2.0,3,"Action, Adventure, Drama, Fantasy",After a horrific alchemy experiment goes wrong...,,Military,Shounen
2,9253,Steins;Gate,TV,9.07,24.0,3.0,14,"Drama, Sci-Fi, Suspense",Eccentric scientist Rintarou Okabe has a never...,Steins;Gate is based on 5pb. and Nitroplus' vi...,"Psychological, Time Travel",
3,38524,Shingeki no Kyojin Season 3 Part 2,TV,9.05,10.0,4.0,21,"Action, Drama, Suspense",Seeking to restore humanity's diminishing hope...,Shingeki no Kyojin Season 3 Part 2 adapts cont...,"Gore, Military, Survival",Shounen
4,28977,Gintama°,TV,9.05,51.0,6.0,345,"Action, Comedy, Sci-Fi","Gintoki, Shinpachi, and Kagura return as the f...",,"Gag Humor, Historical, Parody, Samurai",Shounen
...,...,...,...,...,...,...,...,...,...,...,...,...
995,41389,Tonikaku Kawaii,TV,7.85,12.0,976.0,263,"Comedy, Romance",Nasa Yuzaki is determined to leave his name in...,,,Shounen
996,50634,Love Me: Kaede to Suzu The Animation,OVA,7.85,3.0,NaN,5269,Hentai,Kaede is the student council president and is ...,,,
997,1921,Urusei Yatsura 2: Beautiful Dreamer,Movie,7.85,1.0,979.0,4950,"Action, Adventure, Comedy, Drama, Romance, Sci-Fi","Not all is normal in Tomobiki, even by its sta...",,,Shounen
998,283,Akage no Anne,TV,7.85,50.0,969.0,3413,Drama,"Life is not easy for Anne Shirley, an 11-year-...",,Historical,
999,949,Top wo Nerae! Gunbuster,OVA,7.85,6.0,978.0,1803,"Action, Award Winning, Comedy, Drama, Sci-Fi","In the near future, humanity has taken its fir...",Winner of the 1990 Seiun Award for Best Dramat...,"Mecha, Military, Space",

In [ ]:
all_demographics = df_anime['demographics'].str.split(', ', expand=True).stack().unique()
all_demographics

array(['Shounen', '', 'Seinen', 'Shoujo', 'Josei', 'Kids'], dtype=object)

In [ ]:
# Lista de animes favoritos de um certo usuario

fav_list = []

def get_user_fav(user):
  fav_anime = jikan.users(username=user, extension='favorites')
  for anime in fav_anime['data']['anime']:
    anime_title = {
        'title': anime.get('title')
    }
    fav_list.append(anime_title)

username = 'JoaoVictorDBP'
get_user_fav(username)

In [ ]:
df_fav = pd.DataFrame(fav_list)
df_fav

                    title
0      Mob Psycho 100 III
1       Sousou no Frieren
2          Girls Band Cry
3   Vinland Saga Season 2
4             Steins;Gate
5       Tengoku Daimakyou
6       Takopii no Genzai
7              Death Note
8          Koe no Katachi
9  Hunter x Hunter (2011)